name: CI/CD

on:
    push:
        paths:
            - src/**
            - public/**
            - styles/**
            - .github/workflows/ci-cd.yml
            - package.json
            - package-lock.json
            - next.config.js
    pull_request:

jobs:
    build:
        name: Build
        if: ${{ !contains(github.event.head_commit.message, '[failing]') }}
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Install dependencies
                run: npm ci

            -   name: Build
                run: npm run build
                env:
                    NODE_ENV: production

            -   name: Run and check if up
                env:
                    PORT: 8080
                run: |
                    npm run start &
                    for attempt in {1..20}; do
                        sleep 1
                        if (curl http://localhost:8080 -f); then
                            OK=1
                            break
                        fi
                        echo "Waiting for server to start ($attempt/20)..."
                    done
                    if [ $OK ]; then
                        exit 0
                    else
                        echo "Failed to connect to server."
                        exit 1
                    fi
                    kill -9 $(lsof -t -i:8080)

